# -*- coding: utf-8 -*-
"""杂.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOU1Rg8e8rVqluSVPl8XIs5OHpdPaWyf
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# load dataset
digits = datasets.load_digits()
X = digits.data
y = digits.target

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# train model
model = SVC()
model.fit(X_train, y_train)

# test
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)